version: "3.9"

services:
  migrate:
    image: "migrate/migrate"
    networks:
      - healthNet
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:123321@postgres:5432/medician_auth?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=medician_auth
    networks:
      - healthNet
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  auth:
    container_name: medical-auth
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - healthNet
    ports:
      - "8081:8081"
      - "50050:50050"


networks:
  healthNet:
    name: healthNet
    driver: bridge

volumes:
  postgres_data:
  migrations: